name: Terraform CI/CD

on:
  push:
    paths:
      - '**.tf'
      - '**.yml'
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  terraform:
    uses: './.github/workflows/terraform.yml'
    with:
      terraform_working_directory: './terraform'
      terraform_environments_directory: './terraform/environments'
      terraform_modules_directory: './terraform/modules'
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_ORGANIZATION: ${{ secrets.TF_ORGANIZATION }}
